// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  chatId: __t.u64().primaryKey(),
  roundId: __t.string(),
  address: __t.string(),
  username: __t.string(),
  message: __t.string(),
  pfpUrl: __t.string(),
  timestamp: __t.i64(),
  msgType: __t.string(),
});
