// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";

export type Checkins = {
  checkinId: bigint,
  userIdentifier: string,
  username: string,
  pfpUrl: string,
  checkinDate: bigint,
  pointsEarned: bigint,
  streakCount: bigint,
};
let _cached_Checkins_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const Checkins = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_Checkins_type_value) return _cached_Checkins_type_value;
    _cached_Checkins_type_value = __AlgebraicTypeValue.Product({ elements: [] });
    _cached_Checkins_type_value.value.elements.push(
      { name: "checkinId", algebraicType: __AlgebraicTypeValue.U64 },
      { name: "userIdentifier", algebraicType: __AlgebraicTypeValue.String },
      { name: "username", algebraicType: __AlgebraicTypeValue.String },
      { name: "pfpUrl", algebraicType: __AlgebraicTypeValue.String },
      { name: "checkinDate", algebraicType: __AlgebraicTypeValue.I64 },
      { name: "pointsEarned", algebraicType: __AlgebraicTypeValue.I64 },
      { name: "streakCount", algebraicType: __AlgebraicTypeValue.I64 },
    );
    return _cached_Checkins_type_value;
  },

  serialize(writer: __BinaryWriter, value: Checkins): void {
    __AlgebraicTypeValue.serializeValue(writer, Checkins.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): Checkins {
    return __AlgebraicTypeValue.deserializeValue(reader, Checkins.getTypeScriptAlgebraicType());
  },

}

export default Checkins;


