// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  guessId: __t.u64().primaryKey(),
  roundId: __t.u64(),
  fid: __t.i64(),
  username: __t.string(),
  guess: __t.i64(),
  pfpUrl: __t.option(__t.string()),
  submittedAt: __t.i64(),
});
