// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.8.0 (commit 549f84c80846137ec1ef7468d01673a329c0501f).

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";

// Import and reexport all reducer arg types
import { CreateRound } from "./create_round_reducer.ts";
export { CreateRound };
import { DailyCheckin } from "./daily_checkin_reducer.ts";
export { DailyCheckin };
import { EndRoundManually } from "./end_round_manually_reducer.ts";
export { EndRoundManually };
import { GetActiveRound } from "./get_active_round_reducer.ts";
export { GetActiveRound };
import { GetPrizeConfig } from "./get_prize_config_reducer.ts";
export { GetPrizeConfig };
import { SavePrizeConfig } from "./save_prize_config_reducer.ts";
export { SavePrizeConfig };
import { SendChatMessage } from "./send_chat_message_reducer.ts";
export { SendChatMessage };
import { SubmitGuess } from "./submit_guess_reducer.ts";
export { SubmitGuess };
import { TickRounds } from "./tick_rounds_reducer.ts";
export { TickRounds };
import { UpdateRoundResult } from "./update_round_result_reducer.ts";
export { UpdateRoundResult };

// Import and reexport all table handle types
import { ChatMessagesTableHandle } from "./chat_messages_table.ts";
export { ChatMessagesTableHandle };
import { CheckinsTableHandle } from "./checkins_table.ts";
export { CheckinsTableHandle };
import { GuessesTableHandle } from "./guesses_table.ts";
export { GuessesTableHandle };
import { LogsTableHandle } from "./logs_table.ts";
export { LogsTableHandle };
import { PrizeConfigTableHandle } from "./prize_config_table.ts";
export { PrizeConfigTableHandle };
import { RoundTimerTableHandle } from "./round_timer_table.ts";
export { RoundTimerTableHandle };
import { RoundsTableHandle } from "./rounds_table.ts";
export { RoundsTableHandle };
import { UserStatsTableHandle } from "./user_stats_table.ts";
export { UserStatsTableHandle };

// Import and reexport all types
import { ChatMessage } from "./chat_message_type.ts";
export { ChatMessage };
import { CheckIn } from "./check_in_type.ts";
export { CheckIn };
import { Guess } from "./guess_type.ts";
export { Guess };
import { LogEvent } from "./log_event_type.ts";
export { LogEvent };
import { PrizeConfig } from "./prize_config_type.ts";
export { PrizeConfig };
import { Round } from "./round_type.ts";
export { Round };
import { RoundTimer } from "./round_timer_type.ts";
export { RoundTimer };
import { UserStat } from "./user_stat_type.ts";
export { UserStat };

const REMOTE_MODULE = {
  tables: {
    chat_messages: {
      tableName: "chat_messages" as const,
      rowType: ChatMessage.getTypeScriptAlgebraicType(),
      primaryKey: "chatId",
      primaryKeyInfo: {
        colName: "chatId",
        colType: (ChatMessage.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    checkins: {
      tableName: "checkins" as const,
      rowType: CheckIn.getTypeScriptAlgebraicType(),
      primaryKey: "checkinId",
      primaryKeyInfo: {
        colName: "checkinId",
        colType: (CheckIn.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    guesses: {
      tableName: "guesses" as const,
      rowType: Guess.getTypeScriptAlgebraicType(),
      primaryKey: "guessId",
      primaryKeyInfo: {
        colName: "guessId",
        colType: (Guess.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    logs: {
      tableName: "logs" as const,
      rowType: LogEvent.getTypeScriptAlgebraicType(),
      primaryKey: "logId",
      primaryKeyInfo: {
        colName: "logId",
        colType: (LogEvent.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    prize_config: {
      tableName: "prize_config" as const,
      rowType: PrizeConfig.getTypeScriptAlgebraicType(),
      primaryKey: "configId",
      primaryKeyInfo: {
        colName: "configId",
        colType: (PrizeConfig.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    round_timer: {
      tableName: "round_timer" as const,
      rowType: RoundTimer.getTypeScriptAlgebraicType(),
      primaryKey: "scheduledId",
      primaryKeyInfo: {
        colName: "scheduledId",
        colType: (RoundTimer.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    rounds: {
      tableName: "rounds" as const,
      rowType: Round.getTypeScriptAlgebraicType(),
      primaryKey: "roundId",
      primaryKeyInfo: {
        colName: "roundId",
        colType: (Round.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
    user_stats: {
      tableName: "user_stats" as const,
      rowType: UserStat.getTypeScriptAlgebraicType(),
      primaryKey: "statId",
      primaryKeyInfo: {
        colName: "statId",
        colType: (UserStat.getTypeScriptAlgebraicType() as __AlgebraicTypeVariants.Product).value.elements[0].algebraicType,
      },
    },
  },
  reducers: {
    create_round: {
      reducerName: "create_round",
      argsType: CreateRound.getTypeScriptAlgebraicType(),
    },
    daily_checkin: {
      reducerName: "daily_checkin",
      argsType: DailyCheckin.getTypeScriptAlgebraicType(),
    },
    end_round_manually: {
      reducerName: "end_round_manually",
      argsType: EndRoundManually.getTypeScriptAlgebraicType(),
    },
    get_active_round: {
      reducerName: "get_active_round",
      argsType: GetActiveRound.getTypeScriptAlgebraicType(),
    },
    get_prize_config: {
      reducerName: "get_prize_config",
      argsType: GetPrizeConfig.getTypeScriptAlgebraicType(),
    },
    save_prize_config: {
      reducerName: "save_prize_config",
      argsType: SavePrizeConfig.getTypeScriptAlgebraicType(),
    },
    send_chat_message: {
      reducerName: "send_chat_message",
      argsType: SendChatMessage.getTypeScriptAlgebraicType(),
    },
    submit_guess: {
      reducerName: "submit_guess",
      argsType: SubmitGuess.getTypeScriptAlgebraicType(),
    },
    tick_rounds: {
      reducerName: "tick_rounds",
      argsType: TickRounds.getTypeScriptAlgebraicType(),
    },
    update_round_result: {
      reducerName: "update_round_result",
      argsType: UpdateRoundResult.getTypeScriptAlgebraicType(),
    },
  },
  versionInfo: {
    cliVersion: "1.8.0",
  },
  // Constructors which are used by the DbConnectionImpl to
  // extract type information from the generated RemoteModule.
  //
  // NOTE: This is not strictly necessary for `eventContextConstructor` because
  // all we do is build a TypeScript object which we could have done inside the
  // SDK, but if in the future we wanted to create a class this would be
  // necessary because classes have methods, so we'll keep it.
  eventContextConstructor: (imp: __DbConnectionImpl, event: __Event<Reducer>) => {
    return {
      ...(imp as DbConnection),
      event
    }
  },
  dbViewConstructor: (imp: __DbConnectionImpl) => {
    return new RemoteTables(imp);
  },
  reducersConstructor: (imp: __DbConnectionImpl, setReducerFlags: SetReducerFlags) => {
    return new RemoteReducers(imp, setReducerFlags);
  },
  setReducerFlagsConstructor: () => {
    return new SetReducerFlags();
  }
}

// A type representing all the possible variants of a reducer.
export type Reducer = never
| { name: "CreateRound", args: CreateRound }
| { name: "DailyCheckin", args: DailyCheckin }
| { name: "EndRoundManually", args: EndRoundManually }
| { name: "GetActiveRound", args: GetActiveRound }
| { name: "GetPrizeConfig", args: GetPrizeConfig }
| { name: "SavePrizeConfig", args: SavePrizeConfig }
| { name: "SendChatMessage", args: SendChatMessage }
| { name: "SubmitGuess", args: SubmitGuess }
| { name: "TickRounds", args: TickRounds }
| { name: "UpdateRoundResult", args: UpdateRoundResult }
;

export class RemoteReducers {
  constructor(private connection: __DbConnectionImpl, private setCallReducerFlags: SetReducerFlags) {}

  createRound(roundNumber: bigint, durationMinutes: bigint, prize: string, blockNumber: bigint | undefined) {
    const __args = { roundNumber, durationMinutes, prize, blockNumber };
    let __writer = new __BinaryWriter(1024);
    CreateRound.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("create_round", __argsBuffer, this.setCallReducerFlags.createRoundFlags);
  }

  onCreateRound(callback: (ctx: ReducerEventContext, roundNumber: bigint, durationMinutes: bigint, prize: string, blockNumber: bigint | undefined) => void) {
    this.connection.onReducer("create_round", callback);
  }

  removeOnCreateRound(callback: (ctx: ReducerEventContext, roundNumber: bigint, durationMinutes: bigint, prize: string, blockNumber: bigint | undefined) => void) {
    this.connection.offReducer("create_round", callback);
  }

  dailyCheckin(userIdentifier: string, username: string, pfpUrl: string) {
    const __args = { userIdentifier, username, pfpUrl };
    let __writer = new __BinaryWriter(1024);
    DailyCheckin.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("daily_checkin", __argsBuffer, this.setCallReducerFlags.dailyCheckinFlags);
  }

  onDailyCheckin(callback: (ctx: ReducerEventContext, userIdentifier: string, username: string, pfpUrl: string) => void) {
    this.connection.onReducer("daily_checkin", callback);
  }

  removeOnDailyCheckin(callback: (ctx: ReducerEventContext, userIdentifier: string, username: string, pfpUrl: string) => void) {
    this.connection.offReducer("daily_checkin", callback);
  }

  endRoundManually(roundId: bigint) {
    const __args = { roundId };
    let __writer = new __BinaryWriter(1024);
    EndRoundManually.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("end_round_manually", __argsBuffer, this.setCallReducerFlags.endRoundManuallyFlags);
  }

  onEndRoundManually(callback: (ctx: ReducerEventContext, roundId: bigint) => void) {
    this.connection.onReducer("end_round_manually", callback);
  }

  removeOnEndRoundManually(callback: (ctx: ReducerEventContext, roundId: bigint) => void) {
    this.connection.offReducer("end_round_manually", callback);
  }

  getActiveRound() {
    this.connection.callReducer("get_active_round", new Uint8Array(0), this.setCallReducerFlags.getActiveRoundFlags);
  }

  onGetActiveRound(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("get_active_round", callback);
  }

  removeOnGetActiveRound(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("get_active_round", callback);
  }

  getPrizeConfig() {
    this.connection.callReducer("get_prize_config", new Uint8Array(0), this.setCallReducerFlags.getPrizeConfigFlags);
  }

  onGetPrizeConfig(callback: (ctx: ReducerEventContext) => void) {
    this.connection.onReducer("get_prize_config", callback);
  }

  removeOnGetPrizeConfig(callback: (ctx: ReducerEventContext) => void) {
    this.connection.offReducer("get_prize_config", callback);
  }

  savePrizeConfig(jackpotAmount: bigint, firstPlaceAmount: bigint, secondPlaceAmount: bigint, currencyType: string, tokenContractAddress: string) {
    const __args = { jackpotAmount, firstPlaceAmount, secondPlaceAmount, currencyType, tokenContractAddress };
    let __writer = new __BinaryWriter(1024);
    SavePrizeConfig.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("save_prize_config", __argsBuffer, this.setCallReducerFlags.savePrizeConfigFlags);
  }

  onSavePrizeConfig(callback: (ctx: ReducerEventContext, jackpotAmount: bigint, firstPlaceAmount: bigint, secondPlaceAmount: bigint, currencyType: string, tokenContractAddress: string) => void) {
    this.connection.onReducer("save_prize_config", callback);
  }

  removeOnSavePrizeConfig(callback: (ctx: ReducerEventContext, jackpotAmount: bigint, firstPlaceAmount: bigint, secondPlaceAmount: bigint, currencyType: string, tokenContractAddress: string) => void) {
    this.connection.offReducer("save_prize_config", callback);
  }

  sendChatMessage(roundId: string, address: string, username: string, message: string, pfpUrl: string, msgType: string) {
    const __args = { roundId, address, username, message, pfpUrl, msgType };
    let __writer = new __BinaryWriter(1024);
    SendChatMessage.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("send_chat_message", __argsBuffer, this.setCallReducerFlags.sendChatMessageFlags);
  }

  onSendChatMessage(callback: (ctx: ReducerEventContext, roundId: string, address: string, username: string, message: string, pfpUrl: string, msgType: string) => void) {
    this.connection.onReducer("send_chat_message", callback);
  }

  removeOnSendChatMessage(callback: (ctx: ReducerEventContext, roundId: string, address: string, username: string, message: string, pfpUrl: string, msgType: string) => void) {
    this.connection.offReducer("send_chat_message", callback);
  }

  submitGuess(roundId: bigint, fid: bigint, username: string, guess: bigint, pfpUrl: string | undefined) {
    const __args = { roundId, fid, username, guess, pfpUrl };
    let __writer = new __BinaryWriter(1024);
    SubmitGuess.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("submit_guess", __argsBuffer, this.setCallReducerFlags.submitGuessFlags);
  }

  onSubmitGuess(callback: (ctx: ReducerEventContext, roundId: bigint, fid: bigint, username: string, guess: bigint, pfpUrl: string | undefined) => void) {
    this.connection.onReducer("submit_guess", callback);
  }

  removeOnSubmitGuess(callback: (ctx: ReducerEventContext, roundId: bigint, fid: bigint, username: string, guess: bigint, pfpUrl: string | undefined) => void) {
    this.connection.offReducer("submit_guess", callback);
  }

  tickRounds(timer: RoundTimer) {
    const __args = { timer };
    let __writer = new __BinaryWriter(1024);
    TickRounds.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("tick_rounds", __argsBuffer, this.setCallReducerFlags.tickRoundsFlags);
  }

  onTickRounds(callback: (ctx: ReducerEventContext, timer: RoundTimer) => void) {
    this.connection.onReducer("tick_rounds", callback);
  }

  removeOnTickRounds(callback: (ctx: ReducerEventContext, timer: RoundTimer) => void) {
    this.connection.offReducer("tick_rounds", callback);
  }

  updateRoundResult(roundId: bigint, actualTxCount: bigint, blockHash: string, winningFid: bigint) {
    const __args = { roundId, actualTxCount, blockHash, winningFid };
    let __writer = new __BinaryWriter(1024);
    UpdateRoundResult.serialize(__writer, __args);
    let __argsBuffer = __writer.getBuffer();
    this.connection.callReducer("update_round_result", __argsBuffer, this.setCallReducerFlags.updateRoundResultFlags);
  }

  onUpdateRoundResult(callback: (ctx: ReducerEventContext, roundId: bigint, actualTxCount: bigint, blockHash: string, winningFid: bigint) => void) {
    this.connection.onReducer("update_round_result", callback);
  }

  removeOnUpdateRoundResult(callback: (ctx: ReducerEventContext, roundId: bigint, actualTxCount: bigint, blockHash: string, winningFid: bigint) => void) {
    this.connection.offReducer("update_round_result", callback);
  }

}

export class SetReducerFlags {
  createRoundFlags: __CallReducerFlags = 'FullUpdate';
  createRound(flags: __CallReducerFlags) {
    this.createRoundFlags = flags;
  }

  dailyCheckinFlags: __CallReducerFlags = 'FullUpdate';
  dailyCheckin(flags: __CallReducerFlags) {
    this.dailyCheckinFlags = flags;
  }

  endRoundManuallyFlags: __CallReducerFlags = 'FullUpdate';
  endRoundManually(flags: __CallReducerFlags) {
    this.endRoundManuallyFlags = flags;
  }

  getActiveRoundFlags: __CallReducerFlags = 'FullUpdate';
  getActiveRound(flags: __CallReducerFlags) {
    this.getActiveRoundFlags = flags;
  }

  getPrizeConfigFlags: __CallReducerFlags = 'FullUpdate';
  getPrizeConfig(flags: __CallReducerFlags) {
    this.getPrizeConfigFlags = flags;
  }

  savePrizeConfigFlags: __CallReducerFlags = 'FullUpdate';
  savePrizeConfig(flags: __CallReducerFlags) {
    this.savePrizeConfigFlags = flags;
  }

  sendChatMessageFlags: __CallReducerFlags = 'FullUpdate';
  sendChatMessage(flags: __CallReducerFlags) {
    this.sendChatMessageFlags = flags;
  }

  submitGuessFlags: __CallReducerFlags = 'FullUpdate';
  submitGuess(flags: __CallReducerFlags) {
    this.submitGuessFlags = flags;
  }

  tickRoundsFlags: __CallReducerFlags = 'FullUpdate';
  tickRounds(flags: __CallReducerFlags) {
    this.tickRoundsFlags = flags;
  }

  updateRoundResultFlags: __CallReducerFlags = 'FullUpdate';
  updateRoundResult(flags: __CallReducerFlags) {
    this.updateRoundResultFlags = flags;
  }

}

export class RemoteTables {
  constructor(private connection: __DbConnectionImpl) {}

  get chatMessages(): ChatMessagesTableHandle<'chat_messages'> {
    // clientCache is a private property
    return new ChatMessagesTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<ChatMessage>(REMOTE_MODULE.tables.chat_messages));
  }

  get checkins(): CheckinsTableHandle<'checkins'> {
    // clientCache is a private property
    return new CheckinsTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<CheckIn>(REMOTE_MODULE.tables.checkins));
  }

  get guesses(): GuessesTableHandle<'guesses'> {
    // clientCache is a private property
    return new GuessesTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<Guess>(REMOTE_MODULE.tables.guesses));
  }

  get logs(): LogsTableHandle<'logs'> {
    // clientCache is a private property
    return new LogsTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<LogEvent>(REMOTE_MODULE.tables.logs));
  }

  get prizeConfig(): PrizeConfigTableHandle<'prize_config'> {
    // clientCache is a private property
    return new PrizeConfigTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<PrizeConfig>(REMOTE_MODULE.tables.prize_config));
  }

  get roundTimer(): RoundTimerTableHandle<'round_timer'> {
    // clientCache is a private property
    return new RoundTimerTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<RoundTimer>(REMOTE_MODULE.tables.round_timer));
  }

  get rounds(): RoundsTableHandle<'rounds'> {
    // clientCache is a private property
    return new RoundsTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<Round>(REMOTE_MODULE.tables.rounds));
  }

  get userStats(): UserStatsTableHandle<'user_stats'> {
    // clientCache is a private property
    return new UserStatsTableHandle((this.connection as unknown as { clientCache: __ClientCache }).clientCache.getOrCreateTable<UserStat>(REMOTE_MODULE.tables.user_stats));
  }
}

export class SubscriptionBuilder extends __SubscriptionBuilderImpl<RemoteTables, RemoteReducers, SetReducerFlags> { }

export class DbConnection extends __DbConnectionImpl<RemoteTables, RemoteReducers, SetReducerFlags> {
  static builder = (): __DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext> => {
    return new __DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext>(REMOTE_MODULE, (imp: __DbConnectionImpl) => imp as DbConnection);
  }
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  }
}

export type EventContext = __EventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type ReducerEventContext = __ReducerEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags, Reducer>;
export type SubscriptionEventContext = __SubscriptionEventContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
export type ErrorContext = __ErrorContextInterface<RemoteTables, RemoteReducers, SetReducerFlags>;
