// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.9.0 (commit e26e7fee502eb84c9d677def7052508c6d219cd6).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  convertToAccessorMap as __convertToAccessorMap,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

// Import and reexport all reducer arg types
import CreateRound from "./create_round_reducer";
export { CreateRound };
import DailyCheckin from "./daily_checkin_reducer";
export { DailyCheckin };
import DeleteSetting from "./delete_setting_reducer";
export { DeleteSetting };
import EndRoundManually from "./end_round_manually_reducer";
export { EndRoundManually };
import GetActiveRound from "./get_active_round_reducer";
export { GetActiveRound };
import GetPrizeConfig from "./get_prize_config_reducer";
export { GetPrizeConfig };
import SavePrizeConfig from "./save_prize_config_reducer";
export { SavePrizeConfig };
import SaveSetting from "./save_setting_reducer";
export { SaveSetting };
import SendChatMessage from "./send_chat_message_reducer";
export { SendChatMessage };
import SubmitGuess from "./submit_guess_reducer";
export { SubmitGuess };
import TickRounds from "./tick_rounds_reducer";
export { TickRounds };
import UpdateRoundResult from "./update_round_result_reducer";
export { UpdateRoundResult };

// Import and reexport all table handle types
import ChatMessagesRow from "./chat_messages_table";
export { ChatMessagesRow };
import CheckinsRow from "./checkins_table";
export { CheckinsRow };
import GuessesRow from "./guesses_table";
export { GuessesRow };
import LogsRow from "./logs_table";
export { LogsRow };
import PrizeConfigRow from "./prize_config_table";
export { PrizeConfigRow };
import RoundTimerRow from "./round_timer_table";
export { RoundTimerRow };
import RoundsRow from "./rounds_table";
export { RoundsRow };
import SettingsRow from "./settings_table";
export { SettingsRow };
import UserStatsRow from "./user_stats_table";
export { UserStatsRow };

// Import and reexport all types
import ChatMessages from "./chat_messages_type";
export { ChatMessages };
import Checkins from "./checkins_type";
export { Checkins };
import Guesses from "./guesses_type";
export { Guesses };
import Logs from "./logs_type";
export { Logs };
import PrizeConfig from "./prize_config_type";
export { PrizeConfig };
import RoundTimer from "./round_timer_type";
export { RoundTimer };
import Rounds from "./rounds_type";
export { Rounds };
import Settings from "./settings_type";
export { Settings };
import UserStats from "./user_stats_type";
export { UserStats };


const tablesSchema = __schema(
  __table({
    name: 'chat_messages',
    indexes: [
      { name: 'chat_id', algorithm: 'btree', columns: [
        'chatId',
      ] },
    ],
    constraints: [
      { name: 'chat_messages_chat_id_key', constraint: 'unique', columns: ['chat_id'] },
    ],
  }, ChatMessagesRow),
  __table({
    name: 'checkins',
    indexes: [
      { name: 'checkin_id', algorithm: 'btree', columns: [
        'checkinId',
      ] },
    ],
    constraints: [
      { name: 'checkins_checkin_id_key', constraint: 'unique', columns: ['checkin_id'] },
    ],
  }, CheckinsRow),
  __table({
    name: 'guesses',
    indexes: [
      { name: 'guess_id', algorithm: 'btree', columns: [
        'guessId',
      ] },
    ],
    constraints: [
      { name: 'guesses_guess_id_key', constraint: 'unique', columns: ['guess_id'] },
    ],
  }, GuessesRow),
  __table({
    name: 'logs',
    indexes: [
      { name: 'log_id', algorithm: 'btree', columns: [
        'logId',
      ] },
    ],
    constraints: [
      { name: 'logs_log_id_key', constraint: 'unique', columns: ['log_id'] },
    ],
  }, LogsRow),
  __table({
    name: 'prize_config',
    indexes: [
      { name: 'config_id', algorithm: 'btree', columns: [
        'configId',
      ] },
    ],
    constraints: [
      { name: 'prize_config_config_id_key', constraint: 'unique', columns: ['config_id'] },
    ],
  }, PrizeConfigRow),
  __table({
    name: 'round_timer',
    indexes: [
      { name: 'scheduled_id', algorithm: 'btree', columns: [
        'scheduledId',
      ] },
    ],
    constraints: [
      { name: 'round_timer_scheduled_id_key', constraint: 'unique', columns: ['scheduled_id'] },
    ],
  }, RoundTimerRow),
  __table({
    name: 'rounds',
    indexes: [
      { name: 'round_id', algorithm: 'btree', columns: [
        'roundId',
      ] },
    ],
    constraints: [
      { name: 'rounds_round_id_key', constraint: 'unique', columns: ['round_id'] },
    ],
  }, RoundsRow),
  __table({
    name: 'settings',
    indexes: [
      { name: 'key', algorithm: 'btree', columns: [
        'key',
      ] },
    ],
    constraints: [
      { name: 'settings_key_key', constraint: 'unique', columns: ['key'] },
    ],
  }, SettingsRow),
  __table({
    name: 'user_stats',
    indexes: [
      { name: 'stat_id', algorithm: 'btree', columns: [
        'statId',
      ] },
      { name: 'user_identifier', algorithm: 'btree', columns: [
        'userIdentifier',
      ] },
    ],
    constraints: [
      { name: 'user_stats_stat_id_key', constraint: 'unique', columns: ['stat_id'] },
      { name: 'user_stats_user_identifier_key', constraint: 'unique', columns: ['user_identifier'] },
    ],
  }, UserStatsRow),
);

const reducersSchema = __reducers(
  __reducerSchema("create_round", CreateRound),
  __reducerSchema("daily_checkin", DailyCheckin),
  __reducerSchema("delete_setting", DeleteSetting),
  __reducerSchema("end_round_manually", EndRoundManually),
  __reducerSchema("get_active_round", GetActiveRound),
  __reducerSchema("get_prize_config", GetPrizeConfig),
  __reducerSchema("save_prize_config", SavePrizeConfig),
  __reducerSchema("save_setting", SaveSetting),
  __reducerSchema("send_chat_message", SendChatMessage),
  __reducerSchema("submit_guess", SubmitGuess),
  __reducerSchema("tick_rounds", TickRounds),
  __reducerSchema("update_round_result", UpdateRoundResult),
);

const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "1.9.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType
>;

export const tables = __convertToAccessorMap(tablesSchema.schemaType.tables);
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);


export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;

export class SubscriptionBuilder extends __SubscriptionBuilderImpl<
  typeof REMOTE_MODULE
> {}

export class DbConnectionBuilder extends __DbConnectionBuilder<
  DbConnection
> {}

export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

