// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  roundId: __t.u64().primaryKey(),
  roundNumber: __t.i64(),
  startTime: __t.i64(),
  endTime: __t.i64(),
  durationMinutes: __t.i64(),
  prize: __t.string(),
  status: __t.string(),
  blockNumber: __t.option(__t.i64()),
  actualTxCount: __t.option(__t.i64()),
  winningFid: __t.option(__t.i64()),
  secondPlaceWinnerFid: __t.option(__t.i64()),
  blockHash: __t.option(__t.string()),
  createdAt: __t.i64(),
});
