// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";

export type Round = {
  roundId: bigint,
  roundNumber: bigint,
  startTime: bigint,
  endTime: bigint,
  durationMinutes: bigint,
  prize: string,
  status: string,
  blockNumber: bigint | undefined,
  actualTxCount: bigint | undefined,
  winningFid: bigint | undefined,
  secondPlaceWinnerFid: bigint | undefined,
  blockHash: string | undefined,
  createdAt: bigint,
};
/**
 * An object for generated helper functions.
 */
export const Round = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "roundId", algebraicType: __AlgebraicTypeValue.U64},
        { name: "roundNumber", algebraicType: __AlgebraicTypeValue.I64},
        { name: "startTime", algebraicType: __AlgebraicTypeValue.I64},
        { name: "endTime", algebraicType: __AlgebraicTypeValue.I64},
        { name: "durationMinutes", algebraicType: __AlgebraicTypeValue.I64},
        { name: "prize", algebraicType: __AlgebraicTypeValue.String},
        { name: "status", algebraicType: __AlgebraicTypeValue.String},
        { name: "blockNumber", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.I64)},
        { name: "actualTxCount", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.I64)},
        { name: "winningFid", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.I64)},
        { name: "secondPlaceWinnerFid", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.I64)},
        { name: "blockHash", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String)},
        { name: "createdAt", algebraicType: __AlgebraicTypeValue.I64},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: Round): void {
    __AlgebraicTypeValue.serializeValue(writer, Round.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): Round {
    return __AlgebraicTypeValue.deserializeValue(reader, Round.getTypeScriptAlgebraicType());
  },

}

export default Round;


