// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";

export type SubmitGuess = {
  roundId: bigint,
  fid: bigint,
  username: string,
  guess: bigint,
  pfpUrl: string | undefined,
};
let _cached_SubmitGuess_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const SubmitGuess = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_SubmitGuess_type_value) return _cached_SubmitGuess_type_value;
    _cached_SubmitGuess_type_value = __AlgebraicTypeValue.Product({ elements: [] });
    _cached_SubmitGuess_type_value.value.elements.push(
      { name: "roundId", algebraicType: __AlgebraicTypeValue.U64 },
      { name: "fid", algebraicType: __AlgebraicTypeValue.I64 },
      { name: "username", algebraicType: __AlgebraicTypeValue.String },
      { name: "guess", algebraicType: __AlgebraicTypeValue.I64 },
      { name: "pfpUrl", algebraicType: __AlgebraicTypeValue.createOptionType(__AlgebraicTypeValue.String) },
    );
    return _cached_SubmitGuess_type_value;
  },

  serialize(writer: __BinaryWriter, value: SubmitGuess): void {
    __AlgebraicTypeValue.serializeValue(writer, SubmitGuess.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): SubmitGuess {
    return __AlgebraicTypeValue.deserializeValue(reader, SubmitGuess.getTypeScriptAlgebraicType());
  },

}

export default SubmitGuess;

