// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";
import { UserStat } from "./user_stat_type";
import { type EventContext, type Reducer, RemoteReducers, RemoteTables } from ".";
declare type __keep = [EventContext, Reducer, RemoteReducers, RemoteTables];

/**
 * Table handle for the table `user_stats`.
 *
 * Obtain a handle from the [`userStats`] property on [`RemoteTables`],
 * like `ctx.db.userStats`.
 *
 * Users are encouraged not to explicitly reference this type,
 * but to directly chain method calls,
 * like `ctx.db.userStats.on_insert(...)`.
 */
export class UserStatsTableHandle<TableName extends string> implements __TableHandle<TableName> {
  // phantom type to track the table name
  readonly tableName!: TableName;
  tableCache: __TableCache<UserStat>;

  constructor(tableCache: __TableCache<UserStat>) {
    this.tableCache = tableCache;
  }

  count(): number {
    return this.tableCache.count();
  }

  iter(): Iterable<UserStat> {
    return this.tableCache.iter();
  }
  /**
   * Access to the `statId` unique index on the table `user_stats`,
   * which allows point queries on the field of the same name
   * via the [`UserStatsStatIdUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.userStats.statId().find(...)`.
   *
   * Get a handle on the `statId` unique index on the table `user_stats`.
   */
  statId = {
    // Find the subscribed row whose `statId` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: bigint): UserStat | undefined => {
      for (let row of this.tableCache.iter()) {
        if (__deepEqual(row.statId, col_val)) {
          return row;
        }
      }
    },
  };
  /**
   * Access to the `userIdentifier` unique index on the table `user_stats`,
   * which allows point queries on the field of the same name
   * via the [`UserStatsUserIdentifierUnique.find`] method.
   *
   * Users are encouraged not to explicitly reference this type,
   * but to directly chain method calls,
   * like `ctx.db.userStats.userIdentifier().find(...)`.
   *
   * Get a handle on the `userIdentifier` unique index on the table `user_stats`.
   */
  userIdentifier = {
    // Find the subscribed row whose `userIdentifier` column value is equal to `col_val`,
    // if such a row is present in the client cache.
    find: (col_val: string): UserStat | undefined => {
      for (let row of this.tableCache.iter()) {
        if (__deepEqual(row.userIdentifier, col_val)) {
          return row;
        }
      }
    },
  };

  onInsert = (cb: (ctx: EventContext, row: UserStat) => void) => {
    return this.tableCache.onInsert(cb);
  }

  removeOnInsert = (cb: (ctx: EventContext, row: UserStat) => void) => {
    return this.tableCache.removeOnInsert(cb);
  }

  onDelete = (cb: (ctx: EventContext, row: UserStat) => void) => {
    return this.tableCache.onDelete(cb);
  }

  removeOnDelete = (cb: (ctx: EventContext, row: UserStat) => void) => {
    return this.tableCache.removeOnDelete(cb);
  }

  // Updates are only defined for tables with primary keys.
  onUpdate = (cb: (ctx: EventContext, oldRow: UserStat, newRow: UserStat) => void) => {
    return this.tableCache.onUpdate(cb);
  }

  removeOnUpdate = (cb: (ctx: EventContext, onRow: UserStat, newRow: UserStat) => void) => {
    return this.tableCache.removeOnUpdate(cb);
  }}
