// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  statId: __t.u64().primaryKey(),
  userIdentifier: __t.string(),
  username: __t.string(),
  pfpUrl: __t.string(),
  totalPoints: __t.i64(),
  currentStreak: __t.i64(),
  longestStreak: __t.i64(),
  lastCheckinDate: __t.i64(),
  totalCheckins: __t.i64(),
  createdAt: __t.i64(),
  updatedAt: __t.i64(),
});
